-- Kern Supabase Database Schema (ERD-aligned)

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- PROFILES: linked to Supabase auth users
CREATE TABLE profiles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    wallet_address TEXT UNIQUE NOT NULL,
    username TEXT,
    avatar_url TEXT,
    social_links JSONB DEFAULT '{}'::jsonb,
    reputation_score DOUBLE PRECISION DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CAMPAIGNS: creator vaults and rules
CREATE TABLE campaigns (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    creator_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    vault_pda TEXT UNIQUE NOT NULL,
    source_vod_url TEXT,
    reward_rate NUMERIC NOT NULL,
    total_budget NUMERIC NOT NULL,
    ai_rules JSONB DEFAULT '{}'::jsonb,
    soft_rules TEXT,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'funding', 'active', 'completed')),
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CLIPS: submissions from clippers
CREATE TABLE clips (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    campaign_id UUID REFERENCES campaigns(id) ON DELETE CASCADE,
    clipper_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    video_url TEXT UNIQUE NOT NULL,
    platform TEXT NOT NULL CHECK (platform IN ('tiktok', 'reels', 'shorts')),
    initial_views BIGINT DEFAULT 0,
    current_views BIGINT DEFAULT 0,
    ai_status TEXT DEFAULT 'pending' CHECK (ai_status IN ('pending', 'verified', 'rejected')),
    ai_score DOUBLE PRECISION DEFAULT 0,
    ai_metadata JSONB DEFAULT '{}'::jsonb,
    status TEXT DEFAULT 'tracking' CHECK (status IN ('tracking', 'paid', 'disputed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- VIEW_SNAPSHOTS: periodic view tracking
CREATE TABLE view_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clip_id UUID REFERENCES clips(id) ON DELETE CASCADE,
    views_count BIGINT NOT NULL,
    delta_views BIGINT NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PAYOUTS: reward settlements
CREATE TABLE payouts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    clip_id UUID REFERENCES clips(id) ON DELETE CASCADE,
    tx_hash TEXT UNIQUE NOT NULL,
    amount_paid NUMERIC NOT NULL,
    paid_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- DISPUTES: clip disputes and verdicts
CREATE TABLE disputes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    clip_id UUID UNIQUE REFERENCES clips(id) ON DELETE CASCADE,
    reason TEXT,
    creator_stake NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
    verdict TEXT CHECK (verdict IN ('valid', 'fraud')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_profiles_wallet ON profiles(wallet_address);
CREATE INDEX idx_campaigns_creator ON campaigns(creator_id);
CREATE INDEX idx_clips_campaign ON clips(campaign_id);
CREATE INDEX idx_clips_clipper ON clips(clipper_id);
CREATE INDEX idx_snapshots_clip ON view_snapshots(clip_id);
CREATE INDEX idx_payouts_clip ON payouts(clip_id);

-- Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE clips ENABLE ROW LEVEL SECURITY;
ALTER TABLE view_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE disputes ENABLE ROW LEVEL SECURITY;

-- Profiles: users can read/update their own profile
CREATE POLICY "profiles_select_own" ON profiles
    FOR SELECT USING (id = auth.uid());
CREATE POLICY "profiles_insert_own" ON profiles
    FOR INSERT WITH CHECK (id = auth.uid());
CREATE POLICY "profiles_update_own" ON profiles
    FOR UPDATE USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- Campaigns: creators can manage their own campaigns; anyone can read active campaigns
CREATE POLICY "campaigns_select_active" ON campaigns
    FOR SELECT USING (status = 'active');
CREATE POLICY "campaigns_select_own" ON campaigns
    FOR SELECT USING (creator_id = auth.uid());
CREATE POLICY "campaigns_insert_own" ON campaigns
    FOR INSERT WITH CHECK (creator_id = auth.uid());
CREATE POLICY "campaigns_update_own" ON campaigns
    FOR UPDATE USING (creator_id = auth.uid()) WITH CHECK (creator_id = auth.uid());

-- Clips: clipper can see/insert own; campaign creator can read clips in their campaign
CREATE POLICY "clips_select_own" ON clips
    FOR SELECT USING (clipper_id = auth.uid());
CREATE POLICY "clips_select_creator" ON clips
    FOR SELECT USING (
        campaign_id IN (
            SELECT id FROM campaigns WHERE creator_id = auth.uid()
        )
    );
CREATE POLICY "clips_insert_own" ON clips
    FOR INSERT WITH CHECK (clipper_id = auth.uid());

-- View snapshots: clipper + campaign creator can read; only service role should insert
CREATE POLICY "view_snapshots_select_clipper" ON view_snapshots
    FOR SELECT USING (
        clip_id IN (
            SELECT id FROM clips WHERE clipper_id = auth.uid()
        )
    );
CREATE POLICY "view_snapshots_select_creator" ON view_snapshots
    FOR SELECT USING (
        clip_id IN (
            SELECT id FROM clips WHERE campaign_id IN (
                SELECT id FROM campaigns WHERE creator_id = auth.uid()
            )
        )
    );

-- Payouts: clipper + campaign creator can read
CREATE POLICY "payouts_select_clipper" ON payouts
    FOR SELECT USING (
        clip_id IN (
            SELECT id FROM clips WHERE clipper_id = auth.uid()
        )
    );
CREATE POLICY "payouts_select_creator" ON payouts
    FOR SELECT USING (
        clip_id IN (
            SELECT id FROM clips WHERE campaign_id IN (
                SELECT id FROM campaigns WHERE creator_id = auth.uid()
            )
        )
    );

-- Disputes: clipper + campaign creator can read; creator can insert disputes
CREATE POLICY "disputes_select_clipper" ON disputes
    FOR SELECT USING (
        clip_id IN (
            SELECT id FROM clips WHERE clipper_id = auth.uid()
        )
    );
CREATE POLICY "disputes_select_creator" ON disputes
    FOR SELECT USING (
        clip_id IN (
            SELECT id FROM clips WHERE campaign_id IN (
                SELECT id FROM campaigns WHERE creator_id = auth.uid()
            )
        )
    );
CREATE POLICY "disputes_insert_creator" ON disputes
    FOR INSERT WITH CHECK (
        clip_id IN (
            SELECT id FROM clips WHERE campaign_id IN (
                SELECT id FROM campaigns WHERE creator_id = auth.uid()
            )
        )
    );
